// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Addingrelationsbetweentables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingrelationsbetweentables));
        
        string IMigrationMetadata.Id
        {
            get { return "202005042119488_Adding relations between tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
